[versions]
activity = "1.13.0"
appcompat = "1.7.1"
composeBom = "2026.06.01"
composeNavigation = "2.9.8"
coroutines = "1.11.0"
datastore = "1.2.1"
detekt = "2.0.0-alpha.5"
documentfile = "1.1.0"
hilt = "2.60.1"
hiltNavigation = "1.4.0"
immutableCollections = "0.5.1"
junit = "4.13.2"
jupiter = "6.1.2"
kmpWheelPicker = "0.3.0"
kotlin = "2.4.10"
kotlinxSerialization = "1.11.0"
lifecycle = "2.11.0"
paging = "3.5.0"
reorderable = "3.1.0"
robolectric = "4.16"
room = "2.8.4"
testCore = "1.7.0"
viewmodel = "2.11.0"
timber = "5.0.1"
work = "2.11.2"
turbine = "1.2.1"
vico = "3.2.3"

androidPlugin = "9.3.1"
kspPlugin = "2.3.10"
ktfmtPlugin = "0.26.0"
ossLicensesPlugin = "0.13.0"

[libraries]
activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidPlugin" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "kspPlugin" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material-icons = { module = "androidx.compose.material:material-icons-core" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
compose-navigation-material = { module = "androidx.compose.material:material-navigation" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
detekt-rules-ktlint-wrapper = { module = "dev.detekt:detekt-rules-ktlint-wrapper", version.ref = "detekt" }
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
hilt-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }
immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "immutableCollections" }
junit = { module = "junit:junit", version.ref = "junit" }
jupiter = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "jupiter" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "jupiter" }
kmpWheelPicker = { module = "com.swmansion.kmpwheelpicker:kmp-wheel-picker", version.ref = "kmpWheelPicker" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
test-core = { module = "androidx.test:core", version.ref = "testCore" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
vico = { module = "com.patrykandpatrick.vico:compose-android", version.ref = "vico" }
viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewmodel" }
work = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }

[bundles]
kotlin = ["kotlin-stdlib", "kotlin-coroutines"]
hilt = ["hilt-android", "hilt-navigation"]
ui = ["compose-ui", "compose-ui-preview", "compose-material-icons", "compose-material3", "compose-navigation", "vico", "immutable-collections", "compose-navigation-material", "compose-material3-adaptive"]
testing = ["junit", "jupiter", "kotlin-test", "kotlin-coroutines-test", "turbine"]

[plugins]
application = { id = "com.android.application", version.ref = "androidPlugin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinXSerialization = { id = "kotlinx-serialization" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
library = { id = "com.android.library", version.ref = "androidPlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmtPlugin" }
oss-licenses = { id = "com.google.android.gms.oss-licenses-plugin", version.ref = "ossLicensesPlugin" }
